# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    # Node.js
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "1"

# Install scripts. (runs after repo cloning)
install:
  # Get the Node version with matching major & minor numbers
  - ps: Install-Product node $env:nodejs_version
  # Log HTTP requests
  - npm config set loglevel http
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
